# Generated by Django 3.2.5 on 2021-10-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211007_1144'),
        ('home', '0007_auto_20211007_2014'),
    ]

    operations = [
    ]
